services:
  # Backend API Service
  - type: web
    name: reguchain-watch-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///app/data/reguchain.db
      - key: FAISS_INDEX_PATH
        value: /app/faiss_index/index
      - key: EMBEDDINGS_PROVIDER
        value: huggingface
      - key: EMBEDDINGS_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: EMBEDDINGS_DIMENSION
        value: 384
      - key: LLM_PROVIDER
        value: groq
      - key: LLM_MODEL
        value: llama-3.1-8b-instant
      - key: LLM_TEMPERATURE
        value: 0.3
      - key: PATHWAY_MODE
        value: streaming
      - key: PATHWAY_STREAMING_MODE
        value: realtime
      - key: PATHWAY_PERSISTENCE_BACKEND
        value: filesystem
      - key: PATHWAY_PERSISTENCE_PATH
        value: /app/pathway_data
      - key: PATHWAY_KEY
        sync: false
      - key: RISK_SCORE_THRESHOLD
        value: 50
      - key: TRANSACTION_THRESHOLD
        value: 10000
    healthCheckPath: /api/realtime/health
    disk:
      name: reguchain-data
      mountPath: /app/data
      sizeGB: 1

  # Background Worker for Ingestion (Optional)
  - type: worker
    name: reguchain-watch-ingester
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    dockerCommand: python -m app.ingest_worker
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:///app/data/reguchain.db
      - key: FAISS_INDEX_PATH
        value: /app/faiss_index/index
    disk:
      name: reguchain-data
      mountPath: /app/data
      sizeGB: 1

# Cron Jobs for periodic data refresh
cronJobs:
  - name: reguchain-data-refresh
    schedule: "0 */6 * * *"  # Every 6 hours
    command: curl -X POST https://reguchain-watch-api.onrender.com/api/ingest/refresh
