services:
  # ReguChain Pathway-Powered Backend
  - type: web
    name: reguchain-pathway-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      # Core API Keys
      - key: OPENROUTER_API_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: PATHWAY_KEY
        sync: false
      
      # Database & Storage
      - key: DATABASE_URL
        value: sqlite:///app/data/reguchain.db
      - key: VECTOR_DB_TYPE
        value: faiss
      - key: FAISS_INDEX_PATH
        value: /app/data/faiss_index
      
      # LLM Configuration (OpenRouter + Mistral)
      - key: LLM_PROVIDER
        value: openrouter
      - key: LLM_MODEL
        value: mistralai/mistral-7b-instruct
      - key: EMBEDDINGS_MODEL
        value: text-embedding-3-small
      - key: EMBEDDINGS_PROVIDER
        value: openrouter
      - key: EMBEDDINGS_DIMENSION
        value: 1536
      - key: LLM_TEMPERATURE
        value: 0.2
      
      # Pathway Configuration
      - key: PATHWAY_MODE
        value: streaming
      - key: PATHWAY_STREAMING_MODE
        value: realtime
      - key: PATHWAY_PERSISTENCE_BACKEND
        value: filesystem
      - key: PATHWAY_PERSISTENCE_PATH
        value: /app/data/pathway_data
      - key: PATHWAY_MONITORING_LEVEL
        value: info
      
      # Risk Thresholds
      - key: RISK_SCORE_THRESHOLD
        value: 70
      - key: TRANSACTION_THRESHOLD
        value: 10000.0
      
      # Data Sources
      - key: OFAC_SDN_URL
        value: https://www.treasury.gov/ofac/downloads/sdn.csv
      - key: OFAC_CONSOLIDATED_URL
        value: https://www.treasury.gov/ofac/downloads/consolidated/consolidated.xml
      - key: SEC_RSS_URL
        value: https://www.sec.gov/news/pressreleases.rss
      - key: CFTC_RSS_URL
        value: https://www.cftc.gov/news/rss
      - key: FINRA_RSS_URL
        value: https://www.finra.org/about/news-center/rss
      - key: NEWSAPI_ENDPOINT
        value: https://newsdata.io/api/1/news
      
      # Blockchain RPCs
      - key: ETHEREUM_RPC_URL
        value: https://eth-mainnet.g.alchemy.com/v2/demo
      - key: POLYGON_RPC_URL
        value: https://polygon-rpc.com
    
    healthCheckPath: /api/health
    disk:
      name: reguchain-data
      mountPath: /app/data
      sizeGB: 1

  # Frontend (Next.js)
  - type: web
    name: reguchain-pathway-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://reguchain-pathway-api.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://reguchain-pathway-api.onrender.com
    healthCheckPath: /

# Cron Jobs for system health
cronJobs:
  - name: reguchain-health-check
    schedule: "*/15 * * * *"  # Every 15 minutes
    command: curl -f https://reguchain-pathway-api.onrender.com/api/health
